name: doctor
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.6.0
  lottie: ^2.7.0
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  get_storage: ^2.1.1
  sliding_clipped_nav_bar: ^3.1.0+4
  table_calendar: ^3.1.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  yandex_mapkit: ^3.4.0
  geolocator: ^11.0.0
  zoom_tap_animation: ^1.1.0
  google_fonts: ^6.2.1
  mask_text_input_formatter: ^2.9.0
  supabase_flutter: ^2.4.0
  sizer: ^2.0.15
  flutter_form_builder: ^9.2.1
  flutter_masked_text2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/svg/
    - assets/
    - assets/fonts/
  #   - images/a_dot_ham.jpeg
  # example:
  fonts:
    - family: Roboto # Name of your font family
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic